name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-test:
    name: "Build and test all"
    uses: ./.github/workflows/build_and_test_all.yml
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: build-and-test
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: firmware
          path: ./firmware.bin
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./firmware.bin
